---
# This YAML file defines the search space for hyperparameters for different methods
# Each hyperparameter has a list of possible values to be explored for each method
n_input: 8
space_grid: 144
evals: 10
path:
    xtrain: '../train_test_set/X_train_diabetes.csv'
    ytrain: '../train_test_set/y_train_diabetes.csv'
    xtest: '../train_test_set/X_test_diabetes.csv'
    ytest: '../train_test_set/y_test_diabetes.csv'

grid_search:
    dropout_rate:
        min: 0.0
        max: 0.5
        values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
    learning_rate:
        min: 0.001
        max: 0.1
        values: [0.001, 0.005, 0.01, 0.1]
    neurons:
        min: 4
        max: 128
        values: [4,8,16,32,64,128]

random_search:
    dropout_rate:
        min: 0.0
        max: 0.5
        step: 0.1
    neurons:
        min: 4
        max: 128
    learning_rate:
        min: 0.001
        max: 0.1

hyperopt:
    dropout_rate:
        min: 0.0
        max: 0.5
        step: 0.1
    learning_rate:
        min: 0.001
        max: 0.1
    neurons:
        min: 4
        max: 128
    
    